<a href="https://colab.research.google.com/github/ngwnsaurabh/data_science/blob/master/Sapm_filter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#importing libraries
import pandas as pd
import numpy as np
import string

In [46]:
#reading data
mail = pd.read_csv("spam or ham.csv")
mail.head()

email  label
0   date wed NUMBER aug NUMBER NUMBER NUMBER NUMB...      0
1  martin a posted tassos papadopoulos the greek ...      0
2  man threatens explosion in moscow thursday aug...      0
3  klez the virus that won t die already the most...      0
4   in adding cream to spaghetti carbonara which ...      0

In [47]:
#droppping null value row
mail.dropna(inplace=True)
mail.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2999 entries, 0 to 2999
Data columns (total 2 columns):
email    2999 non-null object
label    2999 non-null int64
dtypes: int64(1), object(1)
memory usage: 70.3+ KB


In [48]:
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [0]:
def text_process(text):
    #lowercasing text
    text = text.lower()
    #Removing punctution marks
    text = text.translate(str.maketrans("","",string.punctuation))
    #Removing stop words
    text = [word for word in text.split() if word not in stopwords.words('english')]
    return " ".join(text)

In [0]:
mail['email'] = mail['email'].apply(text_process)

In [0]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
text_vect = vectorizer.fit_transform(mail['email']).toarray()

In [0]:
from sklearn import model_selection
X_train, X_test, y_train, y_test = model_selection.train_test_split(mail_vect, mail['label'], test_size = 0.2)

In [60]:
from sklearn.linear_model import LogisticRegression
regr = LogisticRegression()
regr.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
from sklearn.metrics import accuracy_score, jaccard_similarity_score

In [62]:
accuracy_score(y_test,regr.predict(X_test))

0.9583333333333334

In [67]:
example_mesaure = np.array(X_train[0].reshape(1,-1))
example_mesaure

array([[0., 0., 0., ..., 0., 0., 0.]])

In [69]:
regr.predict(example_mesaure)

array([0])

In [0]:
def predictor(text):

  instance = text_process(text)
  ins_vect = vectorizer.fit_transform(list(instance))
  return ins_vect


In [0]:
s = "Get 30% off all courses sex money (offer ends soon)Last chance to save! Frantastique is offering a 30% discount on all subscriptions. Even better, if you pay all in one go you’ll get an additional 10% off. Just click the button below before February 4th to claim your discount."
value = text_process(s)
pred = vectorizer.transform([value])

In [87]:
regr.predict(pred)

array([0])